name: Demo Pipeline

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Open the file
        run: echo "My API_KEY is ${{ vars.TEST_VAR }}"
