name: Demo Pipeline

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    enviroment: PROD
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Open the file
        run: echo "My API_KEY is ${{ vars.TEST_VAR }}"